### ISSUE TITLE
Error occurs when executing with ollama specified as LanguageAgent

### ISSUE THREAD

**Issue by shifsa** [mbodiai/embodied-agents#88]
Thanks for releasing such source code.

I have consulted the API reference and am trying to execute the following code using ollama, but an error occurs.
Do you know what could be causing this?

Code:
```
from mbodied.agents.language import LanguageAgent
agent = LanguageAgent(context="You are a robot agent.", model_src="ollama")
response = agent.act("Hello, how are you?")
```
Error:
```
Traceback (most recent call last):
  File "/home/user/embodied-agents/file/test_ollama.py", line 4, in <module>
    response = agent.act("Hello, how are you?")
  File "/home/user/miniconda3/envs/mbodi/lib/python3.10/site-packages/mbodied/agents/language/language_agent.py", line 359, in act
    response = self.actor.predict(message, memory, model=model, **kwargs)
TypeError: HttpxBackend.predict() got multiple values for argument 'model'
```

**Comment by sebbyjp** [comment]
Oh that is indeed a bug, thanks for the catch! Hopefully #89 resolves this issue.

**Comment by shifsa** [comment]
Thank you for the fix. I have confirmed that I can communicate with Ollama. However, I found that if the api_key argument is left as None, an error occurs. Ollama does not require an API key.
```
Traceback (most recent call last):
  File "/home/user/embodied-agents/file/test_ollama.py", line 8, in <module>
    response = agent.act(instruction,model="llama3")
  File "/home/user/embodied-agents/mbodied/agents/language/language_agent.py", line 363, in act
    response = self.actor.predict(message, context=memory, model=model, **kwargs)
  File "/home/user/embodied-agents/mbodied/agents/backends/httpx_backend.py", line 109, in predict
    response = client.post(
  File "/home/user/miniconda3/envs/mbodi/lib/python3.10/site-packages/httpx/_client.py", line 1157, in post
    return self.request(
  File "/home/user/miniconda3/envs/mbodi/lib/python3.10/site-packages/httpx/_client.py", line 824, in request
    request = self.build_request(
  File "/home/user/miniconda3/envs/mbodi/lib/python3.10/site-packages/httpx/_client.py", line 347, in build_request
    headers = self._merge_headers(headers)
  File "/home/user/miniconda3/envs/mbodi/lib/python3.10/site-packages/httpx/_client.py", line 410, in _merge_headers
    merged_headers.update(headers)
  File "/home/user/miniconda3/envs/mbodi/lib/python3.10/site-packages/httpx/_models.py", line 203, in update
    headers = Headers(headers)
  File "/home/user/miniconda3/envs/mbodi/lib/python3.10/site-packages/httpx/_models.py", line 74, in __init__
    self._list = [
  File "/home/user/miniconda3/envs/mbodi/lib/python3.10/site-packages/httpx/_models.py", line 78, in <listcomp>
    normalize_header_value(v, encoding),
  File "/home/user/miniconda3/envs/mbodi/lib/python3.10/site-packages/httpx/_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by nqyy** [comment]
Right! Just made https://github.com/mbodiai/embodied-agents/pull/92
